//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.AutenticarLdapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://delegate.webservices.capaservicios.laaraucana.cl/", ConfigurationName="AutenticarLdapService.AutenticarLdapDelegate")]
    public interface AutenticarLdapDelegate {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://delegate.webservices.capaservicios.laaraucana.cl/AutenticarLdapDelegate/au" +
            "tenticarUsuarioRequest", ReplyAction="http://delegate.webservices.capaservicios.laaraucana.cl/AutenticarLdapDelegate/au" +
            "tenticarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.AutenticarLdapService.autenticarUsuarioResponse autenticarUsuario(CRM.AutenticarLdapService.autenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://delegate.webservices.capaservicios.laaraucana.cl/AutenticarLdapDelegate/au" +
            "tenticarUsuarioRequest", ReplyAction="http://delegate.webservices.capaservicios.laaraucana.cl/AutenticarLdapDelegate/au" +
            "tenticarUsuarioResponse")]
        System.Threading.Tasks.Task<CRM.AutenticarLdapService.autenticarUsuarioResponse> autenticarUsuarioAsync(CRM.AutenticarLdapService.autenticarUsuarioRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.webservices.capaservicios.laaraucana.cl/")]
    public partial class entradaAutenticarLdap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.webservices.capaservicios.laaraucana.cl/")]
    public partial class log : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codRespuestaField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codRespuesta {
            get {
                return this.codRespuestaField;
            }
            set {
                this.codRespuestaField = value;
                this.RaisePropertyChanged("codRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.webservices.capaservicios.laaraucana.cl/")]
    public partial class autenticacionLDAP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool debeCambiarClaveField;
        
        private string idUsuarioField;
        
        private log logField;
        
        private string ultimoLoginField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool debeCambiarClave {
            get {
                return this.debeCambiarClaveField;
            }
            set {
                this.debeCambiarClaveField = value;
                this.RaisePropertyChanged("debeCambiarClave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public log log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("log");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ultimoLogin {
            get {
                return this.ultimoLoginField;
            }
            set {
                this.ultimoLoginField = value;
                this.RaisePropertyChanged("ultimoLogin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuario", WrapperNamespace="http://delegate.webservices.capaservicios.laaraucana.cl/", IsWrapped=true)]
    public partial class autenticarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://delegate.webservices.capaservicios.laaraucana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CRM.AutenticarLdapService.entradaAutenticarLdap entradaWS;
        
        public autenticarUsuarioRequest() {
        }
        
        public autenticarUsuarioRequest(CRM.AutenticarLdapService.entradaAutenticarLdap entradaWS) {
            this.entradaWS = entradaWS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioResponse", WrapperNamespace="http://delegate.webservices.capaservicios.laaraucana.cl/", IsWrapped=true)]
    public partial class autenticarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://delegate.webservices.capaservicios.laaraucana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CRM.AutenticarLdapService.autenticacionLDAP @return;
        
        public autenticarUsuarioResponse() {
        }
        
        public autenticarUsuarioResponse(CRM.AutenticarLdapService.autenticacionLDAP @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutenticarLdapDelegateChannel : CRM.AutenticarLdapService.AutenticarLdapDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticarLdapDelegateClient : System.ServiceModel.ClientBase<CRM.AutenticarLdapService.AutenticarLdapDelegate>, CRM.AutenticarLdapService.AutenticarLdapDelegate {
        
        public AutenticarLdapDelegateClient() {
        }
        
        public AutenticarLdapDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticarLdapDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticarLdapDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticarLdapDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.AutenticarLdapService.autenticarUsuarioResponse CRM.AutenticarLdapService.AutenticarLdapDelegate.autenticarUsuario(CRM.AutenticarLdapService.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuario(request);
        }
        
        public CRM.AutenticarLdapService.autenticacionLDAP autenticarUsuario(CRM.AutenticarLdapService.entradaAutenticarLdap entradaWS) {
            CRM.AutenticarLdapService.autenticarUsuarioRequest inValue = new CRM.AutenticarLdapService.autenticarUsuarioRequest();
            inValue.entradaWS = entradaWS;
            CRM.AutenticarLdapService.autenticarUsuarioResponse retVal = ((CRM.AutenticarLdapService.AutenticarLdapDelegate)(this)).autenticarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.AutenticarLdapService.autenticarUsuarioResponse> CRM.AutenticarLdapService.AutenticarLdapDelegate.autenticarUsuarioAsync(CRM.AutenticarLdapService.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.AutenticarLdapService.autenticarUsuarioResponse> autenticarUsuarioAsync(CRM.AutenticarLdapService.entradaAutenticarLdap entradaWS) {
            CRM.AutenticarLdapService.autenticarUsuarioRequest inValue = new CRM.AutenticarLdapService.autenticarUsuarioRequest();
            inValue.entradaWS = entradaWS;
            return ((CRM.AutenticarLdapService.AutenticarLdapDelegate)(this)).autenticarUsuarioAsync(inValue);
        }
    }
}
