//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.ConsultaDatosAfiliadoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/", ConfigurationName="ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate")]
    public interface ConsultaDatosAfiliadoDelegate {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://delegate.consultadatosafiliado.laaraucana.cl/ConsultaDatosAfiliadoDelegate" +
            "/obtenerDatosAfiliadoRequest", ReplyAction="http://delegate.consultadatosafiliado.laaraucana.cl/ConsultaDatosAfiliadoDelegate" +
            "/obtenerDatosAfiliadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoResponse obtenerDatosAfiliado(CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://delegate.consultadatosafiliado.laaraucana.cl/ConsultaDatosAfiliadoDelegate" +
            "/obtenerDatosAfiliadoRequest", ReplyAction="http://delegate.consultadatosafiliado.laaraucana.cl/ConsultaDatosAfiliadoDelegate" +
            "/obtenerDatosAfiliadoResponse")]
        System.Threading.Tasks.Task<CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoResponse> obtenerDatosAfiliadoAsync(CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/")]
    public partial class datosAfiliado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private persona datosAfiliado1Field;
        
        private datosEmpresa datosEmpresaField;
        
        private datosEmpresa[] empresasField;
        
        private datosEmpresa[] empresasACargoField;
        
        private log logField;
        
        private perfiles perfilField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("datosAfiliado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public persona datosAfiliado1 {
            get {
                return this.datosAfiliado1Field;
            }
            set {
                this.datosAfiliado1Field = value;
                this.RaisePropertyChanged("datosAfiliado1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public datosEmpresa datosEmpresa {
            get {
                return this.datosEmpresaField;
            }
            set {
                this.datosEmpresaField = value;
                this.RaisePropertyChanged("datosEmpresa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("empresas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public datosEmpresa[] empresas {
            get {
                return this.empresasField;
            }
            set {
                this.empresasField = value;
                this.RaisePropertyChanged("empresas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("empresasACargo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public datosEmpresa[] empresasACargo {
            get {
                return this.empresasACargoField;
            }
            set {
                this.empresasACargoField = value;
                this.RaisePropertyChanged("empresasACargo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public log log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("log");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public perfiles perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
                this.RaisePropertyChanged("perfil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string codAreaTelFijoField;
        
        private string codComunaField;
        
        private string direccionField;
        
        private string emailField;
        
        private string estadoCivilField;
        
        private string fechaNacField;
        
        private string nombresField;
        
        private string nroCelularField;
        
        private string nroDptoField;
        
        private string prefijoCelularField;
        
        private string rutAfiliadoField;
        
        private string sexoField;
        
        private string telFijoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codAreaTelFijo {
            get {
                return this.codAreaTelFijoField;
            }
            set {
                this.codAreaTelFijoField = value;
                this.RaisePropertyChanged("codAreaTelFijo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codComuna {
            get {
                return this.codComunaField;
            }
            set {
                this.codComunaField = value;
                this.RaisePropertyChanged("codComuna");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string fechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
                this.RaisePropertyChanged("fechaNac");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string nroCelular {
            get {
                return this.nroCelularField;
            }
            set {
                this.nroCelularField = value;
                this.RaisePropertyChanged("nroCelular");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nroDpto {
            get {
                return this.nroDptoField;
            }
            set {
                this.nroDptoField = value;
                this.RaisePropertyChanged("nroDpto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string prefijoCelular {
            get {
                return this.prefijoCelularField;
            }
            set {
                this.prefijoCelularField = value;
                this.RaisePropertyChanged("prefijoCelular");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string rutAfiliado {
            get {
                return this.rutAfiliadoField;
            }
            set {
                this.rutAfiliadoField = value;
                this.RaisePropertyChanged("rutAfiliado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string telFijo {
            get {
                return this.telFijoField;
            }
            set {
                this.telFijoField = value;
                this.RaisePropertyChanged("telFijo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/")]
    public partial class perfiles : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool esAfiliadoActivoField;
        
        private bool esAfiliadoCesadoField;
        
        private bool esAhorranteField;
        
        private bool esEmpleadoPublicoField;
        
        private bool esEmpresaField;
        
        private bool esEmpresaPublicaField;
        
        private bool esEncargadoEmpresaField;
        
        private bool esIndependienteField;
        
        private bool esPensionadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool esAfiliadoActivo {
            get {
                return this.esAfiliadoActivoField;
            }
            set {
                this.esAfiliadoActivoField = value;
                this.RaisePropertyChanged("esAfiliadoActivo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAfiliadoCesado {
            get {
                return this.esAfiliadoCesadoField;
            }
            set {
                this.esAfiliadoCesadoField = value;
                this.RaisePropertyChanged("esAfiliadoCesado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool esAhorrante {
            get {
                return this.esAhorranteField;
            }
            set {
                this.esAhorranteField = value;
                this.RaisePropertyChanged("esAhorrante");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool esEmpleadoPublico {
            get {
                return this.esEmpleadoPublicoField;
            }
            set {
                this.esEmpleadoPublicoField = value;
                this.RaisePropertyChanged("esEmpleadoPublico");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool esEmpresa {
            get {
                return this.esEmpresaField;
            }
            set {
                this.esEmpresaField = value;
                this.RaisePropertyChanged("esEmpresa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool esEmpresaPublica {
            get {
                return this.esEmpresaPublicaField;
            }
            set {
                this.esEmpresaPublicaField = value;
                this.RaisePropertyChanged("esEmpresaPublica");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool esEncargadoEmpresa {
            get {
                return this.esEncargadoEmpresaField;
            }
            set {
                this.esEncargadoEmpresaField = value;
                this.RaisePropertyChanged("esEncargadoEmpresa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool esIndependiente {
            get {
                return this.esIndependienteField;
            }
            set {
                this.esIndependienteField = value;
                this.RaisePropertyChanged("esIndependiente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool esPensionado {
            get {
                return this.esPensionadoField;
            }
            set {
                this.esPensionadoField = value;
                this.RaisePropertyChanged("esPensionado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/")]
    public partial class log : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codRespuestaField;
        
        private string msgRespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codRespuesta {
            get {
                return this.codRespuestaField;
            }
            set {
                this.codRespuestaField = value;
                this.RaisePropertyChanged("codRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msgRespuesta {
            get {
                return this.msgRespuestaField;
            }
            set {
                this.msgRespuestaField = value;
                this.RaisePropertyChanged("msgRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/")]
    public partial class datosEmpresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private string razonSocialField;
        
        private string rutEmpresaField;
        
        private string tipoEmpresaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rutEmpresa {
            get {
                return this.rutEmpresaField;
            }
            set {
                this.rutEmpresaField = value;
                this.RaisePropertyChanged("rutEmpresa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoEmpresa {
            get {
                return this.tipoEmpresaField;
            }
            set {
                this.tipoEmpresaField = value;
                this.RaisePropertyChanged("tipoEmpresa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosAfiliado", WrapperNamespace="http://delegate.consultadatosafiliado.laaraucana.cl/", IsWrapped=true)]
    public partial class obtenerDatosAfiliadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutAfiliado;
        
        public obtenerDatosAfiliadoRequest() {
        }
        
        public obtenerDatosAfiliadoRequest(string rutAfiliado) {
            this.rutAfiliado = rutAfiliado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosAfiliadoResponse", WrapperNamespace="http://delegate.consultadatosafiliado.laaraucana.cl/", IsWrapped=true)]
    public partial class obtenerDatosAfiliadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://delegate.consultadatosafiliado.laaraucana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CRM.ConsultaDatosAfiliadoService.datosAfiliado @return;
        
        public obtenerDatosAfiliadoResponse() {
        }
        
        public obtenerDatosAfiliadoResponse(CRM.ConsultaDatosAfiliadoService.datosAfiliado @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaDatosAfiliadoDelegateChannel : CRM.ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaDatosAfiliadoDelegateClient : System.ServiceModel.ClientBase<CRM.ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate>, CRM.ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate {
        
        public ConsultaDatosAfiliadoDelegateClient() {
        }
        
        public ConsultaDatosAfiliadoDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaDatosAfiliadoDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDatosAfiliadoDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDatosAfiliadoDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoResponse CRM.ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate.obtenerDatosAfiliado(CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest request) {
            return base.Channel.obtenerDatosAfiliado(request);
        }
        
        public CRM.ConsultaDatosAfiliadoService.datosAfiliado obtenerDatosAfiliado(string rutAfiliado) {
            CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest inValue = new CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest();
            inValue.rutAfiliado = rutAfiliado;
            CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoResponse retVal = ((CRM.ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate)(this)).obtenerDatosAfiliado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoResponse> CRM.ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate.obtenerDatosAfiliadoAsync(CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest request) {
            return base.Channel.obtenerDatosAfiliadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoResponse> obtenerDatosAfiliadoAsync(string rutAfiliado) {
            CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest inValue = new CRM.ConsultaDatosAfiliadoService.obtenerDatosAfiliadoRequest();
            inValue.rutAfiliado = rutAfiliado;
            return ((CRM.ConsultaDatosAfiliadoService.ConsultaDatosAfiliadoDelegate)(this)).obtenerDatosAfiliadoAsync(inValue);
        }
    }
}
