//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WSFonasaCajas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntrActEstLicCCAF", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class EntrActEstLicCCAF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short TipFormularioField;
        
        private int NumFormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecEventoField;
        
        private short TipoEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short TipFormulario {
            get {
                return this.TipFormularioField;
            }
            set {
                if ((this.TipFormularioField.Equals(value) != true)) {
                    this.TipFormularioField = value;
                    this.RaisePropertyChanged("TipFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int NumFormulario {
            get {
                return this.NumFormularioField;
            }
            set {
                if ((this.NumFormularioField.Equals(value) != true)) {
                    this.NumFormularioField = value;
                    this.RaisePropertyChanged("NumFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FecEvento {
            get {
                return this.FecEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.FecEventoField, value) != true)) {
                    this.FecEventoField = value;
                    this.RaisePropertyChanged("FecEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short TipoEvento {
            get {
                return this.TipoEventoField;
            }
            set {
                if ((this.TipoEventoField.Equals(value) != true)) {
                    this.TipoEventoField = value;
                    this.RaisePropertyChanged("TipoEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespActEstLicCCAF", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class RespActEstLicCCAF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRM.WSFonasaCajas.LstResAct[] ListaResActField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GloEstado {
            get {
                return this.GloEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloEstadoField, value) != true)) {
                    this.GloEstadoField = value;
                    this.RaisePropertyChanged("GloEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CRM.WSFonasaCajas.LstResAct[] ListaResAct {
            get {
                return this.ListaResActField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaResActField, value) != true)) {
                    this.ListaResActField = value;
                    this.RaisePropertyChanged("ListaResAct");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LstResAct", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class LstResAct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short TipFormularioField;
        
        private int NumFormularioField;
        
        private short EstActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short TipFormulario {
            get {
                return this.TipFormularioField;
            }
            set {
                if ((this.TipFormularioField.Equals(value) != true)) {
                    this.TipFormularioField = value;
                    this.RaisePropertyChanged("TipFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int NumFormulario {
            get {
                return this.NumFormularioField;
            }
            set {
                if ((this.NumFormularioField.Equals(value) != true)) {
                    this.NumFormularioField = value;
                    this.RaisePropertyChanged("NumFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short EstAct {
            get {
                return this.EstActField;
            }
            set {
                if ((this.EstActField.Equals(value) != true)) {
                    this.EstActField = value;
                    this.RaisePropertyChanged("EstAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GloEstado {
            get {
                return this.GloEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloEstadoField, value) != true)) {
                    this.GloEstadoField = value;
                    this.RaisePropertyChanged("GloEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntrInfEstLicCCAF", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class EntrInfEstLicCCAF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short TipFormularioField;
        
        private int NumFormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecEventoField;
        
        private short TipoEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DerechoSilField;
        
        private int DiasSilPagField;
        
        private long MtoSilPagField;
        
        private int DiasCotPagField;
        
        private long MtoCotPagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short TipFormulario {
            get {
                return this.TipFormularioField;
            }
            set {
                if ((this.TipFormularioField.Equals(value) != true)) {
                    this.TipFormularioField = value;
                    this.RaisePropertyChanged("TipFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int NumFormulario {
            get {
                return this.NumFormularioField;
            }
            set {
                if ((this.NumFormularioField.Equals(value) != true)) {
                    this.NumFormularioField = value;
                    this.RaisePropertyChanged("NumFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FecEvento {
            get {
                return this.FecEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.FecEventoField, value) != true)) {
                    this.FecEventoField = value;
                    this.RaisePropertyChanged("FecEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short TipoEvento {
            get {
                return this.TipoEventoField;
            }
            set {
                if ((this.TipoEventoField.Equals(value) != true)) {
                    this.TipoEventoField = value;
                    this.RaisePropertyChanged("TipoEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DerechoSil {
            get {
                return this.DerechoSilField;
            }
            set {
                if ((object.ReferenceEquals(this.DerechoSilField, value) != true)) {
                    this.DerechoSilField = value;
                    this.RaisePropertyChanged("DerechoSil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int DiasSilPag {
            get {
                return this.DiasSilPagField;
            }
            set {
                if ((this.DiasSilPagField.Equals(value) != true)) {
                    this.DiasSilPagField = value;
                    this.RaisePropertyChanged("DiasSilPag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long MtoSilPag {
            get {
                return this.MtoSilPagField;
            }
            set {
                if ((this.MtoSilPagField.Equals(value) != true)) {
                    this.MtoSilPagField = value;
                    this.RaisePropertyChanged("MtoSilPag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int DiasCotPag {
            get {
                return this.DiasCotPagField;
            }
            set {
                if ((this.DiasCotPagField.Equals(value) != true)) {
                    this.DiasCotPagField = value;
                    this.RaisePropertyChanged("DiasCotPag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long MtoCotPag {
            get {
                return this.MtoCotPagField;
            }
            set {
                if ((this.MtoCotPagField.Equals(value) != true)) {
                    this.MtoCotPagField = value;
                    this.RaisePropertyChanged("MtoCotPag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespInfEstLicCCAF", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class RespInfEstLicCCAF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRM.WSFonasaCajas.LstResInf[] ListaResActField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GloEstado {
            get {
                return this.GloEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloEstadoField, value) != true)) {
                    this.GloEstadoField = value;
                    this.RaisePropertyChanged("GloEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CRM.WSFonasaCajas.LstResInf[] ListaResAct {
            get {
                return this.ListaResActField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaResActField, value) != true)) {
                    this.ListaResActField = value;
                    this.RaisePropertyChanged("ListaResAct");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LstResInf", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class LstResInf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short TipFormularioField;
        
        private int NumFormularioField;
        
        private short EstActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short TipFormulario {
            get {
                return this.TipFormularioField;
            }
            set {
                if ((this.TipFormularioField.Equals(value) != true)) {
                    this.TipFormularioField = value;
                    this.RaisePropertyChanged("TipFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int NumFormulario {
            get {
                return this.NumFormularioField;
            }
            set {
                if ((this.NumFormularioField.Equals(value) != true)) {
                    this.NumFormularioField = value;
                    this.RaisePropertyChanged("NumFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short EstAct {
            get {
                return this.EstActField;
            }
            set {
                if ((this.EstActField.Equals(value) != true)) {
                    this.EstActField = value;
                    this.RaisePropertyChanged("EstAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GloEstado {
            get {
                return this.GloEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloEstadoField, value) != true)) {
                    this.GloEstadoField = value;
                    this.RaisePropertyChanged("GloEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespLicCertifTrab", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class RespLicCertifTrab : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtApellidoPatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtApellidoMatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtSexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtFechaNacimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtCodEstBenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtDescEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GloEstado {
            get {
                return this.GloEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloEstadoField, value) != true)) {
                    this.GloEstadoField = value;
                    this.RaisePropertyChanged("GloEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExtApellidoPat {
            get {
                return this.ExtApellidoPatField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtApellidoPatField, value) != true)) {
                    this.ExtApellidoPatField = value;
                    this.RaisePropertyChanged("ExtApellidoPat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExtApellidoMat {
            get {
                return this.ExtApellidoMatField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtApellidoMatField, value) != true)) {
                    this.ExtApellidoMatField = value;
                    this.RaisePropertyChanged("ExtApellidoMat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtNombres {
            get {
                return this.ExtNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtNombresField, value) != true)) {
                    this.ExtNombresField = value;
                    this.RaisePropertyChanged("ExtNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ExtSexo {
            get {
                return this.ExtSexoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtSexoField, value) != true)) {
                    this.ExtSexoField = value;
                    this.RaisePropertyChanged("ExtSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExtFechaNacimi {
            get {
                return this.ExtFechaNacimiField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtFechaNacimiField, value) != true)) {
                    this.ExtFechaNacimiField = value;
                    this.RaisePropertyChanged("ExtFechaNacimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExtCodEstBen {
            get {
                return this.ExtCodEstBenField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtCodEstBenField, value) != true)) {
                    this.ExtCodEstBenField = value;
                    this.RaisePropertyChanged("ExtCodEstBen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ExtDescEstado {
            get {
                return this.ExtDescEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtDescEstadoField, value) != true)) {
                    this.ExtDescEstadoField = value;
                    this.RaisePropertyChanged("ExtDescEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespVerEstLicCCAF", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class RespVerEstLicCCAF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRM.WSFonasaCajas.LstEstados[] ListaEstadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GloEstado {
            get {
                return this.GloEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloEstadoField, value) != true)) {
                    this.GloEstadoField = value;
                    this.RaisePropertyChanged("GloEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CRM.WSFonasaCajas.LstEstados[] ListaEstados {
            get {
                return this.ListaEstadosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEstadosField, value) != true)) {
                    this.ListaEstadosField = value;
                    this.RaisePropertyChanged("ListaEstados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LstEstados", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class LstEstados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecEventoField;
        
        private short CodEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FecEvento {
            get {
                return this.FecEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.FecEventoField, value) != true)) {
                    this.FecEventoField = value;
                    this.RaisePropertyChanged("FecEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public short CodEstado {
            get {
                return this.CodEstadoField;
            }
            set {
                if ((this.CodEstadoField.Equals(value) != true)) {
                    this.CodEstadoField = value;
                    this.RaisePropertyChanged("CodEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespConFormLCC", Namespace="http://WSFonaCajasNM/")]
    [System.SerializableAttribute()]
    public partial class RespConFormLCC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloEstadoField;
        
        private short CodResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GloResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GloEstado {
            get {
                return this.GloEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloEstadoField, value) != true)) {
                    this.GloEstadoField = value;
                    this.RaisePropertyChanged("GloEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short CodResultado {
            get {
                return this.CodResultadoField;
            }
            set {
                if ((this.CodResultadoField.Equals(value) != true)) {
                    this.CodResultadoField = value;
                    this.RaisePropertyChanged("CodResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GloResultado {
            get {
                return this.GloResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GloResultadoField, value) != true)) {
                    this.GloResultadoField = value;
                    this.RaisePropertyChanged("GloResultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WSFonaCajasNM/", ConfigurationName="WSFonasaCajas.WSFonaCajasSoap")]
    public interface WSFonaCajasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CodigoUsuario del espacio de nombres http://WSFonaCajasNM/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/ActEstLicCCAF", ReplyAction="*")]
        CRM.WSFonasaCajas.ActEstLicCCAFResponse ActEstLicCCAF(CRM.WSFonasaCajas.ActEstLicCCAFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/ActEstLicCCAF", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.ActEstLicCCAFResponse> ActEstLicCCAFAsync(CRM.WSFonasaCajas.ActEstLicCCAFRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CodigoUsuario del espacio de nombres http://WSFonaCajasNM/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/InfEstLicCCAF", ReplyAction="*")]
        CRM.WSFonasaCajas.InfEstLicCCAFResponse InfEstLicCCAF(CRM.WSFonasaCajas.InfEstLicCCAFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/InfEstLicCCAF", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.InfEstLicCCAFResponse> InfEstLicCCAFAsync(CRM.WSFonasaCajas.InfEstLicCCAFRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RutBeneficiario del espacio de nombres http://WSFonaCajasNM/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/LicCertifTrab", ReplyAction="*")]
        CRM.WSFonasaCajas.LicCertifTrabResponse LicCertifTrab(CRM.WSFonasaCajas.LicCertifTrabRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/LicCertifTrab", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.LicCertifTrabResponse> LicCertifTrabAsync(CRM.WSFonasaCajas.LicCertifTrabRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CodigoUsuario del espacio de nombres http://WSFonaCajasNM/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/VerEstLicCCAF", ReplyAction="*")]
        CRM.WSFonasaCajas.VerEstLicCCAFResponse VerEstLicCCAF(CRM.WSFonasaCajas.VerEstLicCCAFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/VerEstLicCCAF", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.VerEstLicCCAFResponse> VerEstLicCCAFAsync(CRM.WSFonasaCajas.VerEstLicCCAFRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CodigoUsuario del espacio de nombres http://WSFonaCajasNM/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/ConFormuLCC", ReplyAction="*")]
        CRM.WSFonasaCajas.ConFormuLCCResponse ConFormuLCC(CRM.WSFonasaCajas.ConFormuLCCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSFonaCajasNM/ConFormuLCC", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.ConFormuLCCResponse> ConFormuLCCAsync(CRM.WSFonasaCajas.ConFormuLCCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActEstLicCCAFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActEstLicCCAF", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.ActEstLicCCAFRequestBody Body;
        
        public ActEstLicCCAFRequest() {
        }
        
        public ActEstLicCCAFRequest(CRM.WSFonasaCajas.ActEstLicCCAFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class ActEstLicCCAFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodigoUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short CodigoAsegurador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodigoOperador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CRM.WSFonasaCajas.EntrActEstLicCCAF[] ListaEstLCC;
        
        public ActEstLicCCAFRequestBody() {
        }
        
        public ActEstLicCCAFRequestBody(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, CRM.WSFonasaCajas.EntrActEstLicCCAF[] ListaEstLCC) {
            this.CodigoUsuario = CodigoUsuario;
            this.ClaveUsuario = ClaveUsuario;
            this.CodigoAsegurador = CodigoAsegurador;
            this.CodigoOperador = CodigoOperador;
            this.ListaEstLCC = ListaEstLCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActEstLicCCAFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActEstLicCCAFResponse", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.ActEstLicCCAFResponseBody Body;
        
        public ActEstLicCCAFResponse() {
        }
        
        public ActEstLicCCAFResponse(CRM.WSFonasaCajas.ActEstLicCCAFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class ActEstLicCCAFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.WSFonasaCajas.RespActEstLicCCAF ActEstLicCCAFResult;
        
        public ActEstLicCCAFResponseBody() {
        }
        
        public ActEstLicCCAFResponseBody(CRM.WSFonasaCajas.RespActEstLicCCAF ActEstLicCCAFResult) {
            this.ActEstLicCCAFResult = ActEstLicCCAFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfEstLicCCAFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfEstLicCCAF", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.InfEstLicCCAFRequestBody Body;
        
        public InfEstLicCCAFRequest() {
        }
        
        public InfEstLicCCAFRequest(CRM.WSFonasaCajas.InfEstLicCCAFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class InfEstLicCCAFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodigoUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short CodigoAsegurador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodigoOperador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CRM.WSFonasaCajas.EntrInfEstLicCCAF[] ListaEstLCC;
        
        public InfEstLicCCAFRequestBody() {
        }
        
        public InfEstLicCCAFRequestBody(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, CRM.WSFonasaCajas.EntrInfEstLicCCAF[] ListaEstLCC) {
            this.CodigoUsuario = CodigoUsuario;
            this.ClaveUsuario = ClaveUsuario;
            this.CodigoAsegurador = CodigoAsegurador;
            this.CodigoOperador = CodigoOperador;
            this.ListaEstLCC = ListaEstLCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfEstLicCCAFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfEstLicCCAFResponse", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.InfEstLicCCAFResponseBody Body;
        
        public InfEstLicCCAFResponse() {
        }
        
        public InfEstLicCCAFResponse(CRM.WSFonasaCajas.InfEstLicCCAFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class InfEstLicCCAFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.WSFonasaCajas.RespInfEstLicCCAF InfEstLicCCAFResult;
        
        public InfEstLicCCAFResponseBody() {
        }
        
        public InfEstLicCCAFResponseBody(CRM.WSFonasaCajas.RespInfEstLicCCAF InfEstLicCCAFResult) {
            this.InfEstLicCCAFResult = InfEstLicCCAFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LicCertifTrabRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LicCertifTrab", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.LicCertifTrabRequestBody Body;
        
        public LicCertifTrabRequest() {
        }
        
        public LicCertifTrabRequest(CRM.WSFonasaCajas.LicCertifTrabRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class LicCertifTrabRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RutBeneficiario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FecCertifica;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RutInstitucion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodigoUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ClaveUsuario;
        
        public LicCertifTrabRequestBody() {
        }
        
        public LicCertifTrabRequestBody(string RutBeneficiario, string FecCertifica, string RutInstitucion, string CodigoUsuario, string ClaveUsuario) {
            this.RutBeneficiario = RutBeneficiario;
            this.FecCertifica = FecCertifica;
            this.RutInstitucion = RutInstitucion;
            this.CodigoUsuario = CodigoUsuario;
            this.ClaveUsuario = ClaveUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LicCertifTrabResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LicCertifTrabResponse", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.LicCertifTrabResponseBody Body;
        
        public LicCertifTrabResponse() {
        }
        
        public LicCertifTrabResponse(CRM.WSFonasaCajas.LicCertifTrabResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class LicCertifTrabResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.WSFonasaCajas.RespLicCertifTrab LicCertifTrabResult;
        
        public LicCertifTrabResponseBody() {
        }
        
        public LicCertifTrabResponseBody(CRM.WSFonasaCajas.RespLicCertifTrab LicCertifTrabResult) {
            this.LicCertifTrabResult = LicCertifTrabResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerEstLicCCAFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerEstLicCCAF", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.VerEstLicCCAFRequestBody Body;
        
        public VerEstLicCCAFRequest() {
        }
        
        public VerEstLicCCAFRequest(CRM.WSFonasaCajas.VerEstLicCCAFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class VerEstLicCCAFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodigoUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short CodigoAsegurador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodigoOperador;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public short TipFormulario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int NumFormulario;
        
        public VerEstLicCCAFRequestBody() {
        }
        
        public VerEstLicCCAFRequestBody(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, short TipFormulario, int NumFormulario) {
            this.CodigoUsuario = CodigoUsuario;
            this.ClaveUsuario = ClaveUsuario;
            this.CodigoAsegurador = CodigoAsegurador;
            this.CodigoOperador = CodigoOperador;
            this.TipFormulario = TipFormulario;
            this.NumFormulario = NumFormulario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerEstLicCCAFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerEstLicCCAFResponse", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.VerEstLicCCAFResponseBody Body;
        
        public VerEstLicCCAFResponse() {
        }
        
        public VerEstLicCCAFResponse(CRM.WSFonasaCajas.VerEstLicCCAFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class VerEstLicCCAFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.WSFonasaCajas.RespVerEstLicCCAF VerEstLicCCAFResult;
        
        public VerEstLicCCAFResponseBody() {
        }
        
        public VerEstLicCCAFResponseBody(CRM.WSFonasaCajas.RespVerEstLicCCAF VerEstLicCCAFResult) {
            this.VerEstLicCCAFResult = VerEstLicCCAFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConFormuLCCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConFormuLCC", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.ConFormuLCCRequestBody Body;
        
        public ConFormuLCCRequest() {
        }
        
        public ConFormuLCCRequest(CRM.WSFonasaCajas.ConFormuLCCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class ConFormuLCCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodigoUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short CodigoAsegurador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodigoOperador;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public short TipFormulario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int NumFormulario;
        
        public ConFormuLCCRequestBody() {
        }
        
        public ConFormuLCCRequestBody(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, short TipFormulario, int NumFormulario) {
            this.CodigoUsuario = CodigoUsuario;
            this.ClaveUsuario = ClaveUsuario;
            this.CodigoAsegurador = CodigoAsegurador;
            this.CodigoOperador = CodigoOperador;
            this.TipFormulario = TipFormulario;
            this.NumFormulario = NumFormulario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConFormuLCCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConFormuLCCResponse", Namespace="http://WSFonaCajasNM/", Order=0)]
        public CRM.WSFonasaCajas.ConFormuLCCResponseBody Body;
        
        public ConFormuLCCResponse() {
        }
        
        public ConFormuLCCResponse(CRM.WSFonasaCajas.ConFormuLCCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WSFonaCajasNM/")]
    public partial class ConFormuLCCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.WSFonasaCajas.RespConFormLCC ConFormuLCCResult;
        
        public ConFormuLCCResponseBody() {
        }
        
        public ConFormuLCCResponseBody(CRM.WSFonasaCajas.RespConFormLCC ConFormuLCCResult) {
            this.ConFormuLCCResult = ConFormuLCCResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSFonaCajasSoapChannel : CRM.WSFonasaCajas.WSFonaCajasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSFonaCajasSoapClient : System.ServiceModel.ClientBase<CRM.WSFonasaCajas.WSFonaCajasSoap>, CRM.WSFonasaCajas.WSFonaCajasSoap {
        
        public WSFonaCajasSoapClient() {
        }
        
        public WSFonaCajasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSFonaCajasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFonaCajasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFonaCajasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.WSFonasaCajas.ActEstLicCCAFResponse CRM.WSFonasaCajas.WSFonaCajasSoap.ActEstLicCCAF(CRM.WSFonasaCajas.ActEstLicCCAFRequest request) {
            return base.Channel.ActEstLicCCAF(request);
        }
        
        public CRM.WSFonasaCajas.RespActEstLicCCAF ActEstLicCCAF(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, CRM.WSFonasaCajas.EntrActEstLicCCAF[] ListaEstLCC) {
            CRM.WSFonasaCajas.ActEstLicCCAFRequest inValue = new CRM.WSFonasaCajas.ActEstLicCCAFRequest();
            inValue.Body = new CRM.WSFonasaCajas.ActEstLicCCAFRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.ListaEstLCC = ListaEstLCC;
            CRM.WSFonasaCajas.ActEstLicCCAFResponse retVal = ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).ActEstLicCCAF(inValue);
            return retVal.Body.ActEstLicCCAFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.ActEstLicCCAFResponse> CRM.WSFonasaCajas.WSFonaCajasSoap.ActEstLicCCAFAsync(CRM.WSFonasaCajas.ActEstLicCCAFRequest request) {
            return base.Channel.ActEstLicCCAFAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.WSFonasaCajas.ActEstLicCCAFResponse> ActEstLicCCAFAsync(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, CRM.WSFonasaCajas.EntrActEstLicCCAF[] ListaEstLCC) {
            CRM.WSFonasaCajas.ActEstLicCCAFRequest inValue = new CRM.WSFonasaCajas.ActEstLicCCAFRequest();
            inValue.Body = new CRM.WSFonasaCajas.ActEstLicCCAFRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.ListaEstLCC = ListaEstLCC;
            return ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).ActEstLicCCAFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.WSFonasaCajas.InfEstLicCCAFResponse CRM.WSFonasaCajas.WSFonaCajasSoap.InfEstLicCCAF(CRM.WSFonasaCajas.InfEstLicCCAFRequest request) {
            return base.Channel.InfEstLicCCAF(request);
        }
        
        public CRM.WSFonasaCajas.RespInfEstLicCCAF InfEstLicCCAF(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, CRM.WSFonasaCajas.EntrInfEstLicCCAF[] ListaEstLCC) {
            CRM.WSFonasaCajas.InfEstLicCCAFRequest inValue = new CRM.WSFonasaCajas.InfEstLicCCAFRequest();
            inValue.Body = new CRM.WSFonasaCajas.InfEstLicCCAFRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.ListaEstLCC = ListaEstLCC;
            CRM.WSFonasaCajas.InfEstLicCCAFResponse retVal = ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).InfEstLicCCAF(inValue);
            return retVal.Body.InfEstLicCCAFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.InfEstLicCCAFResponse> CRM.WSFonasaCajas.WSFonaCajasSoap.InfEstLicCCAFAsync(CRM.WSFonasaCajas.InfEstLicCCAFRequest request) {
            return base.Channel.InfEstLicCCAFAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.WSFonasaCajas.InfEstLicCCAFResponse> InfEstLicCCAFAsync(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, CRM.WSFonasaCajas.EntrInfEstLicCCAF[] ListaEstLCC) {
            CRM.WSFonasaCajas.InfEstLicCCAFRequest inValue = new CRM.WSFonasaCajas.InfEstLicCCAFRequest();
            inValue.Body = new CRM.WSFonasaCajas.InfEstLicCCAFRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.ListaEstLCC = ListaEstLCC;
            return ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).InfEstLicCCAFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.WSFonasaCajas.LicCertifTrabResponse CRM.WSFonasaCajas.WSFonaCajasSoap.LicCertifTrab(CRM.WSFonasaCajas.LicCertifTrabRequest request) {
            return base.Channel.LicCertifTrab(request);
        }
        
        public CRM.WSFonasaCajas.RespLicCertifTrab LicCertifTrab(string RutBeneficiario, string FecCertifica, string RutInstitucion, string CodigoUsuario, string ClaveUsuario) {
            CRM.WSFonasaCajas.LicCertifTrabRequest inValue = new CRM.WSFonasaCajas.LicCertifTrabRequest();
            inValue.Body = new CRM.WSFonasaCajas.LicCertifTrabRequestBody();
            inValue.Body.RutBeneficiario = RutBeneficiario;
            inValue.Body.FecCertifica = FecCertifica;
            inValue.Body.RutInstitucion = RutInstitucion;
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            CRM.WSFonasaCajas.LicCertifTrabResponse retVal = ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).LicCertifTrab(inValue);
            return retVal.Body.LicCertifTrabResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.LicCertifTrabResponse> CRM.WSFonasaCajas.WSFonaCajasSoap.LicCertifTrabAsync(CRM.WSFonasaCajas.LicCertifTrabRequest request) {
            return base.Channel.LicCertifTrabAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.WSFonasaCajas.LicCertifTrabResponse> LicCertifTrabAsync(string RutBeneficiario, string FecCertifica, string RutInstitucion, string CodigoUsuario, string ClaveUsuario) {
            CRM.WSFonasaCajas.LicCertifTrabRequest inValue = new CRM.WSFonasaCajas.LicCertifTrabRequest();
            inValue.Body = new CRM.WSFonasaCajas.LicCertifTrabRequestBody();
            inValue.Body.RutBeneficiario = RutBeneficiario;
            inValue.Body.FecCertifica = FecCertifica;
            inValue.Body.RutInstitucion = RutInstitucion;
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            return ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).LicCertifTrabAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.WSFonasaCajas.VerEstLicCCAFResponse CRM.WSFonasaCajas.WSFonaCajasSoap.VerEstLicCCAF(CRM.WSFonasaCajas.VerEstLicCCAFRequest request) {
            return base.Channel.VerEstLicCCAF(request);
        }
        
        public CRM.WSFonasaCajas.RespVerEstLicCCAF VerEstLicCCAF(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, short TipFormulario, int NumFormulario) {
            CRM.WSFonasaCajas.VerEstLicCCAFRequest inValue = new CRM.WSFonasaCajas.VerEstLicCCAFRequest();
            inValue.Body = new CRM.WSFonasaCajas.VerEstLicCCAFRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.TipFormulario = TipFormulario;
            inValue.Body.NumFormulario = NumFormulario;
            CRM.WSFonasaCajas.VerEstLicCCAFResponse retVal = ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).VerEstLicCCAF(inValue);
            return retVal.Body.VerEstLicCCAFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.VerEstLicCCAFResponse> CRM.WSFonasaCajas.WSFonaCajasSoap.VerEstLicCCAFAsync(CRM.WSFonasaCajas.VerEstLicCCAFRequest request) {
            return base.Channel.VerEstLicCCAFAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.WSFonasaCajas.VerEstLicCCAFResponse> VerEstLicCCAFAsync(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, short TipFormulario, int NumFormulario) {
            CRM.WSFonasaCajas.VerEstLicCCAFRequest inValue = new CRM.WSFonasaCajas.VerEstLicCCAFRequest();
            inValue.Body = new CRM.WSFonasaCajas.VerEstLicCCAFRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.TipFormulario = TipFormulario;
            inValue.Body.NumFormulario = NumFormulario;
            return ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).VerEstLicCCAFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.WSFonasaCajas.ConFormuLCCResponse CRM.WSFonasaCajas.WSFonaCajasSoap.ConFormuLCC(CRM.WSFonasaCajas.ConFormuLCCRequest request) {
            return base.Channel.ConFormuLCC(request);
        }
        
        public CRM.WSFonasaCajas.RespConFormLCC ConFormuLCC(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, short TipFormulario, int NumFormulario) {
            CRM.WSFonasaCajas.ConFormuLCCRequest inValue = new CRM.WSFonasaCajas.ConFormuLCCRequest();
            inValue.Body = new CRM.WSFonasaCajas.ConFormuLCCRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.TipFormulario = TipFormulario;
            inValue.Body.NumFormulario = NumFormulario;
            CRM.WSFonasaCajas.ConFormuLCCResponse retVal = ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).ConFormuLCC(inValue);
            return retVal.Body.ConFormuLCCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.WSFonasaCajas.ConFormuLCCResponse> CRM.WSFonasaCajas.WSFonaCajasSoap.ConFormuLCCAsync(CRM.WSFonasaCajas.ConFormuLCCRequest request) {
            return base.Channel.ConFormuLCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.WSFonasaCajas.ConFormuLCCResponse> ConFormuLCCAsync(string CodigoUsuario, string ClaveUsuario, short CodigoAsegurador, string CodigoOperador, short TipFormulario, int NumFormulario) {
            CRM.WSFonasaCajas.ConFormuLCCRequest inValue = new CRM.WSFonasaCajas.ConFormuLCCRequest();
            inValue.Body = new CRM.WSFonasaCajas.ConFormuLCCRequestBody();
            inValue.Body.CodigoUsuario = CodigoUsuario;
            inValue.Body.ClaveUsuario = ClaveUsuario;
            inValue.Body.CodigoAsegurador = CodigoAsegurador;
            inValue.Body.CodigoOperador = CodigoOperador;
            inValue.Body.TipFormulario = TipFormulario;
            inValue.Body.NumFormulario = NumFormulario;
            return ((CRM.WSFonasaCajas.WSFonaCajasSoap)(this)).ConFormuLCCAsync(inValue);
        }
    }
}
